### ISSUE TITLE
Losing focus on big files

### ISSUE THREAD

**Issue by Xenap** [EverMCServer/vscode-BetonQuest#3]
From my test it seems that **when the file gets to big**, writing in the textfield becomes impossible.
The page refreshes *(or seems to)* and i **lose focus from the textfield**.

*I am on the `language_support` branch but it also does it on main*

https://github.com/EverMCServer/vscode-BetonQuest/assets/66042272/83ff85be-19cd-4200-baa2-dc92f0ca37a8

For reference the size of the conversation is ~6000 characters, in the video.
*I am using the f5 key to launch the extension, could be because of that*

**Comment by k-jiang** [comment]
This issue is composite of 2 issues:
1. The first time typing in a textfield
2. Typing too fast, causing the newly typed content is overwriten by callback from vscode

Right now only the second one is fixed. I'm still finding the root cause of the first one. If you can provide some clues that would be very helpful ☺️👏.

I will left this issue opened atm.

**Comment by k-jiang** [comment]
https://github.com/Microsoft/vscode/issues/50344
OK, I think I have found it. The document is being updated twice  the first time.

A fix will be pushed soon.

**Comment by k-jiang** [comment]
Version 0.0.4 is released. Please have a look. @Xenap

**Comment by Xenap** [comment]
Works very well, i haven't had any issues, even when doing voodoo magic.
